# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

[project]
name = "opensearch-dashboards-charms-single-kernel"
dynamic = ["version"]
description = "Shared and reusable code for OpenSearch Dashboards charms"
readme = "README.md"
license = "Apache-2.0"
authors = []
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.10,<4.0"


[project.urls]
homepage = "https://github.com/canonical/opensearch-dashboards-single-kernel-library"
repository = "https://github.com/canonical/opensearch-dashboards-single-kernel-library"
"Bug Tracker" = "https://github.com/canonical/opensearch-dashboards-single-kernel-library/issues"
"Matrix" = "https://matrix.to/#/#charmhub-data-platform:ubuntu.com"

[tool.setuptools.packages.find]
where = ["."]
include = ["single_kernel_opensearch_dashboards*"]
exclude = ["terraform*"]

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
markers = ["unstable"]
asyncio_mode = "auto"

# Formatting tools configuration
[tool.black]
line-length = 99
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.codespell]
skip = "*.lock"

[tool.poetry]
requires-poetry = ">=2.0.0"
package-mode = true
packages = [{ include = "single_kernel_opensearch_dashboards" }]
version = "0.0.0"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"
poetry-dynamic-versioning = { version = ">=1.0.0,<2.0.0", extras = ["plugin"] }

[tool.poetry.dependencies]
charmlibs-pathops = "^1.0.1"
python = "^3.10"
tenacity = "^9.1.2"
pyyaml = "^6.0.2"
requests = "^2.32.4"

# TODO: clean any of the notes below and their deps.
jubilant = "^1.8.0"
[tool.poetry.group.charm-libs.dependencies]
# data_platform_libs/v0/data_interfaces.py
ops = "^2.23.2"
# data_platform_libs/v1/upgrade.py
lightkube = "0.19.1"
poetry-core = "^2.1.3"
# tls_certificates_interface/v3/tls_certificates.py
cryptography = "^45.0.4"
jsonschema = "^4.24.0"
# grafana_agent/v0/cos_agent.py requires pydantic
pydantic = ">2, <3"
# grafana_agent/v0/cos_agent.py
cosl = "^1.9.1"
data-platform-helpers = "^0.1.7"

[tool.poetry.group.fmt]
optional = true


[tool.poetry.group.fmt.dependencies]
black = "^25.1.0"
isort = "^6.0.1"


[tool.poetry.group.lint]
optional = true

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
dirty = true
strict = true
fix-shallow-repository = true

[build-system]
requires = ["poetry-core>=2.0", "poetry-dynamic-versioning>=1.0.0,<2.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry.group.lint.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.0.0"
flake8-docstrings = "^1.7.0"
flake8-copyright = "^0.2.4"
flake8-builtins = "^2.5.0"
pyproject-flake8 = "^7.0.0"
pep8-naming = "^0.15.1"
codespell = "^2.4.1"
pyright = "^1.1.402"
typing-extensions = "^4.12.2"
requests = "^2.32.4"
ops = "^2.23.2"


[tool.poetry.group.unit]
optional = true

[tool.poetry.group.unit.dependencies]
charmlibs-pathops = "^1.0.1"
pytest = "^8.4.1"
coverage = { extras = ["toml"], version = "^7.9.1" }
pytest-mock = "^3.14.1"
pyyaml = "^6.0.2"
responses = "^0.25.7"


[tool.poetry.group.integration.dependencies]
charmlibs-pathops = "^1.0.1"
pytest = "^8.4.1"
juju = "^3.6.1.3"
tenacity = "^9.1.2"
coverage = { extras = ["toml"], version = "^7.9.1" }
pytest-asyncio = "^0.21.2"
pytest-operator = "^0.43.1"
pytest-microceph = { git = "https://github.com/canonical/data-platform-workflows", tag = "v32.1.0", subdirectory = "python/pytest_plugins/microceph" }
allure-pytest = "^2.15.0"
allure-pytest-default-results = "^0.1.3"
pytest-playwright = "^0.7.0"
oauth_tools = { git = "https://github.com/canonical/iam-bundle", rev = "921d113325eed156e5b54f97c42e6c50810180c0" }
pyjwt = "^2.10.1"
lightkube = "0.19.1"

[tool.pyright]
include = ["src"]
extraPaths = ["./lib"]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "basic"
reportIncompatibleMethodOverride = false
reportImportCycles = false
reportMissingModuleSource = true
reportMissingImports = false
stubPath = ""
