# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
env_list = lint, unit

[vars]
src_path = {tox_root}/single_kernel_opensearch_dashboards
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
allowlist_externals =
    /bin/bash
    poetry
set_env =
    PYTHONPATH = {[vars]src_path}:{tox_root}/lib
    PY_COLORS = 1
    PIP_IGNORE_INSTALLED = 1
    POETRY_INSTALLER_PARALLEL = false
pass_env =
    poetry

[testenv:format]
description = Apply coding style standards to code
skip_install = true
commands_pre =
    poetry install --only format --no-root
commands =
    poetry lock
    poetry run ruff check --config {tox_root}/pyproject.toml --fix {[vars]all_path}
    poetry run ruff format --config {tox_root}/pyproject.toml {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
skip_install = true
commands_pre =
    poetry install --only lint --no-root
commands =
    poetry check --lock
    poetry run codespell --toml {tox_root}/pyproject.toml {[vars]all_path}
    poetry run ruff check --config {tox_root}/pyproject.toml {[vars]all_path}
    poetry run ruff format --check --config {tox_root}/pyproject.toml --diff {[vars]all_path}

[testenv:unit]
description = Run unit tests
commands_pre =
    poetry install --only main,charm-libs,unit
commands =
    poetry run coverage run --source={[vars]src_path} \
        -m pytest -v --tb native -s {posargs} {[vars]tests_path}/unit
    poetry run coverage report
    poetry run coverage xml

[testenv:integration]
description = Run all integration tests
pass_env =
    CI
    CHARM_UBUNTU_BASE
    AWS_ACCESS_KEY
    AWS_SECRET_KEY
    AZURE_STORAGE_ACCOUNT
    AZURE_SECRET_KEY
    GCP_ACCESS_KEY
    GCP_SECRET_KEY
    GCP_SERVICE_ACCOUNT
    SUBSTRATE
    DASHBOARD_SUBSTRATE
    TEST_TLS
    TEST_TRAEFIK
    TEST_TRAEFIK_TRUST
allowlist_externals =
    {[testenv]allowlist_externals}
    playwright
    poetry
commands_pre =
    poetry install --only integration
    playwright install
    playwright install-deps
commands =
    poetry run pytest -vv --tb native --log-cli-level=INFO --ignore={[vars]tests_path}/unit/ {posargs}
