# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

[tool.poetry]
requires-poetry = ">=2.0.0"
package-mode = false

# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"
markers = ["unstable"]
asyncio_mode = "auto"

# Formatting and linting tools configuration
[tool.ruff]
target-version = "py310"
line-length = 99
exclude = ["lib"]

[tool.ruff.lint]
select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.poetry.dependencies]
python = "^3.10"
opensearch-dashboards-charms-single-kernel = "*"
ops = "^3.8.0"

[tool.poetry.group.charm-libs.dependencies]
ops = "^3.8.0"  # data_platform_libs/v0/data_interfaces.py, data_platform_libs/v1/upgrade.py
pydantic = "^2.13.4"  # data_platform_libs/v1/upgrade.py
lightkube = "0.22.0"  # data_platform_libs/v1/upgrade.py
poetry-core = "^2.4.1"  # data_platform_libs/v1/upgrade.py
cryptography = "^49.0.0"  # tls_certificates_interface/v3/tls_certificates.py
jsonschema = "^4.26.0"  # tls_certificates_interface/v3/tls_certificates.py
cosl = "^1.9.2"  # grafana_agent/v0/cos_agent.py, grafana_k8s/v0/grafana_dashboard.py, loki_k8s/v1/loki_push_api.py

[tool.pyright]
include = ["src"]
extraPaths = ["./lib"]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "basic"
reportIncompatibleMethodOverride = false
reportImportCycles = false
reportMissingModuleSource = true
reportMissingImports = false
stubPath = ""
