# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.
name: Linting, Build and Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.gitignore'
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v52.0.0

  lib-check:
    name: Check libraries
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.7.0
        continue-on-error: true
        with:
          charm-path: ./single_kernel_opensearch_dashboards/
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-labels: false
          fail-build: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      pull-requests: write

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: tox run -e unit

  promtool:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # prometheus snap includes promtool
      - name: Install prometheus snap
        run: sudo snap install prometheus

      - name: Check validity of prometheus alert rules for K8s charm
        run: |
          promtool check rules tests/charms/dashboards_k8s_charm/src/alert_rules/prometheus/*.yaml

      - name: Check validity of prometheus alert rules for VM charm
        run: |
          promtool check rules tests/charms/dashboards_vm_charm/src/alert_rules/prometheus/*.yaml

      - name: Run unit tests for prometheus alert rules
        run: |
          promtool test rules tests/unit/test_alert_rules/*.yaml

  build:
    name: Build Test charm | ${{ matrix.path }}
    uses: ./.github/workflows/build_test_charms.yaml
    with:
      path-to-charm-directory: ${{ matrix.path }}
      artifact-prefix: packed-charm
      cache: false
    permissions:
      contents: read
    strategy:
      matrix:
        path:
          - tests/charms/dashboards_application_charm
          - tests/charms/dashboards_vm_charm
          - tests/charms/dashboards_k8s_charm

  integration-test:
    name: Integration test charm
    needs:
      - lint
      - unit-test
      - build
    uses: $/.github/workflows/integration_test.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      run-on-all-bases: ${{ github.event_name == 'schedule' }}
    permissions:
      contents: write # Needed for Allure Report
